### ISSUE TITLE
Service Accounts

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#10114]
introduce Service Account Principal that supports JWT signed token authentication

XP:
- [x] ~idProviderData filed in User object~ profile filed should be used instead

SIDP
- [x] [Authorization Bearer autologin](https://github.com/enonic/app-standardidprovider/issues/646)

Users App
- [x] enonic/app-users#1689
- [x] enonic/app-users#1724
