### ISSUE TITLE
Auth Lib - CRUD Userstore

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp#5733]
- [ ] Auth Lib - Add function 'getUserstore'
  Mandatory parameter 'params'
    Mandatory parameter 'key'
- [ ] Auth Lib - Add function 'createUserstore'
  Mandatory parameter 'params'
    Mandatory parameter 'name'
    Optional parameter 'displayName' (Use name if missing)
    Optional parameter 'description'
    Optional parameter 'authConfig' (Look at contentLib.create)
- [ ] Auth Lib - Add function 'modifyUserstore'
  Mandatory parameter 'params'
    Mandatory parameter 'key'
    Optional parameter 'editor'

**Comment by sgauruseu** [comment]
1. Click on an UserStore and delete it.
`DefaultErrorHandler.ts:9 Error: Id cannot be null or empty
    at Object.assert (http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1510561847/admin/common/js/_all.js:13:23)
    at UserStoreKey.UserItemKey (http://localhost:8080/admin/tool/com.enonic.xp.app.users/main/_/asset/com.enonic.xp.app.users:1510561847/admin/common/js/_all.js:12327:26)`
