### ISSUE TITLE
7.0 checklist

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp#6405]
- [ ] Upgrade script
- [ ] New CLI for Toolbox
- [ ] Use PurpleJS in XP
- [ ] Kubernetes
- [ ] Java 11
- [ ] More effective storage of versions
- [x] HTML Area model
- [ ] Image/CSS styles in HTML Area
- [ ] New user store/ID provider model (improvement)
- [ ] Separate index from data
- [ ] Move Mustache to a separate lib
- [ ] Query - Consistent path handling
- [ ] Remove all backwards compatibility hacks
