### ISSUE TITLE
Code improvements and cleanup

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#7361]
- [x] Run IntelliJ provided Analyze -> Code Cleanup
- [x] Remove all unused Java imports
- [x] Refactor places with UnsupportedEncodingException thrown
- [x] Replace com.google.common.base.Charsets with java.nio.charset.StandardCharsets

- [x] In some places (mostly tests) Immutable* can be replaced with `Set.of` `Map.of` `List.of` or similar. Use  unmodifiable/immutable Java 11 map and set with caution: they are very memory efficient, but not necessarily speed efficient. 

- [x] Places with Maps.uniqueIndex could be revisited.

- [x] Guava BaseEncoding.base64() has alternative java.util.Base64

- [x] Guava Predicate, Function, Supplier are obsolete

- [x] Guava Joiner can be replaced by StringJoiner or Collectors.joining)

-  [x] Guava Iterables mostly useless in Java 11

-  [x] Enumeration, Hashtable minimize usage

**Comment by rymsha** [comment]
Ongoing project moved to https://github.com/enonic/xp/projects/8
