### ISSUE TITLE
Migrate to Jakarta EE dependencies

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#7619]
https://jakarta.ee/ is new home for many javax dependencies.

- [x] javax.mail
- [x] javax.activation
- [x] javax.annotation
- [x] javax.validation
- [ ] ~~javax.servlet~~ (need new Jetty)
- [ ] ~~javax.websocket~~ (need new Jetty)
- [x] javax.ws.rs
- [ ] javax.xml.bind (separate issue)

**Comment by rymsha** [comment]
https://webtide.com/renaming-from-javax-to-jakarta/
