### ISSUE TITLE
libs compile dependency on XP Java api(s) repackage XP classes

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8171]
It is not affecting core libs (check that, please), but create hard to debug classloader issues for libs in dedicated git repositories.
Recent example: enonic/app-snapshotter#12

Need to go through all lib repositories and change api dependencies from `compile` to `compileOnly`.

A side effect: applications that still use Java API directly may stop compiling, but it is better that they have a floating cloassloader bug. Such applications should specify api dependency directly and not rely on lib transitive dependencies.

Related issues:
- [x] [lib-graphql](https://github.com/enonic/lib-graphql/issues/40)
- [x] [lib-xslt](https://github.com/enonic/lib-xslt/issues/8) 
- [x] [lib-react4xp](https://github.com/enonic/lib-react4xp/issues/75) 
- [x] [lib-geoip](https://github.com/enonic/lib-geoip/issues/3)
- [x] [lib-markdown](https://github.com/enonic/lib-markdown/issues/6)
- [x] [lib-git](https://github.com/enonic/lib-git/issues/1) - not published
- [x] [lib-apibuilder](https://github.com/enonic/lib-apibuilder/issues/1) - not published
- [x] [lib-sql](https://github.com/enonic/lib-sql/issues/13)
- [x] [lib-license](https://github.com/enonic/lib-license/issues/17)
- [x] [lib-qrcode](https://github.com/enonic/lib-qrcode/issues/4)
- [x] [lib-router](https://github.com/enonic/lib-router/issues/13)
- [x] [lib-mustache](https://github.com/enonic/lib-mustache/issues/11)
- [x] [lib-thymeleaf](https://github.com/enonic/lib-thymeleaf/issues/16)
- [ ] Update `lib-graphql-playground` after release `lib-mustache`

**Comment by anatol-sialitski** [comment]
Related issues:
- [lib-graphql](https://github.com/enonic/lib-graphql/issues/40) Fix compile dependency
