### ISSUE TITLE
Restart XP without restarting JVM after dump or snapshot restore

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8221]
Currently after dump-restore or snapshot-restore XP may become in inconsistent state, if snapshot/dump were way too different from existing structure (like different apps, or different versions of apps, or different version of XP, or running apps expect its data to be never rolled back).
#8086 fix makes it more more appearing., ~and XP will basically issue a warning and ask to restart entire cluster.~ XP restarts Felix OSGi framework

There might be cases when downtime after snapshot-restore should be minimal, and in general it is possible to redo XP OSGi init.

- [x]  application bundles should be reinstalled
- [x] all caches must be invalidated (in a way they don't get repopulated due to front-end requests, so it should be a global lock)
- [ ] all task threads should be shut down.
- [x] bootstrap (initialization of required indices - like `system.ouditlog` )should be redone. Because snapshot restore may remove it.

**Comment by rymsha** [comment]
#8219 takes care of most requirements. 
Tasks can still survive though ind introduce ugly memory leaks.

**Comment by rymsha** [comment]
This is working and used in production. The only drawback is well known and mitigated by XP hard reboot, if needed
