### ISSUE TITLE
Deploy SNAPSHOTs  from Github Actions

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8248]

**Comment by rymsha** [comment]
also enonic/xp-distro#129

**Comment by rymsha** [comment]
todo:

- [ ] Content Studio pipeline
- [ ] remove xp-distro unstable 
- [ ] cleanup shapshots from public repo
