### ISSUE TITLE
Automate xp docker libs and apps releases

### ISSUE THREAD

**Issue by rymsha** [enonic/xp#8254]
Example is in this repository https://github.com/enonic/lib-graphql

To make a release:
Commit `gradle.properties` with the following properties
```
projectName=lib-graphql ### identifies artifact name for uploading to Github binaries
version=1.1.2 ### should be a release version (SNAPSHOTs) are not released
```

What already works
- [x] deployment of snapshots to maven repo
- [x] deployment of releases to maven repo
- [x] tagging and releasing in Github
- [x] deployment of releases to Github binaries

Todo:
- [x] automatically write release notes
- [ ] automatically update market.enonic.com
- [x] ~template for release_name~
- [x] release xp, system apps and distro
- [x] release docker enonic/docker-xp7#3

**Comment by rymsha** [comment]
Little interest in automating release notes on market.
Open a new issue, if needed.
